### ISSUE TITLE
Sound volumes are way too loud

### ISSUE THREAD

**Issue by JasonB32** [Schuemi/fMSX-go#1]
Hi,

The first volume level is low and that's fine, but the second one is pretty extreme and the third volume level i feel may blow the speaker over time.

Thank you so much for making this btw, I'm so impressed, I love MSX!!!

**Comment by kamotswind** [comment]
The lowest volume is also somewhat distorted. The volume will need to be adjusted in the emulator before it is passed off to the ADC. You may want to check the emulator here https://github.com/OtherCrashOverride/go-play/tree/master/smsplusgx-go for some guidance.
