### ISSUE TITLE
Ikari Warriors for MSX 2 doesn't work?

### ISSUE THREAD

**Issue by JasonB32** [Schuemi/fMSX-go#2]
It just loads to a blue screen, I wonder what could be going on. It works on my other devices hmm.

It's a great game is why I submitted this ticket LOL It's better than the NES version by far.

**Comment by Schuemi** [comment]
I'll take a look at that. My favorite is Metal Gear Solid 2, currently only the first version works. This also has to work ;)

**Comment by JasonB32** [comment]
Awesome Thank you! 

I love the Metal Gears I heard the first Metal Gear on MSX was Konami's first version ever!

**Comment by kamotswind** [comment]
@Schuemi Metal Gear 2 - Solid Snake (1990) works for me using the default settings. It may be a problem with the ROM you are testing or your SD card.

**Comment by Schuemi** [comment]
Ikari Warriors is a tough nut. I didn't get the ROM version to work, I think it uses a not documented opcode or something, BUT:

There is a disk version out there called "Ikari Warriors (1987)(SNK)(JP).dsk". This version works now.

**Comment by JasonB32** [comment]
Yes I got the .dsk version working by choosing 50 hz option in beginning, 60 hz didn't work, but player is very faint, enemies and entire game besides player are completely fine. Thank you!!!
