### ISSUE TITLE
Please update roms path to match current standards

### ISSUE THREAD

**Issue by kamotswind** [Schuemi/fMSX-go#5]
The games folder \roms\msx\games should simply be \roms\msx

Having the subfolder "games" is not consistent with the other emulators for the platform and will cause confusion.

**Comment by Schuemi** [comment]
I wanted to separate the games from the bios files. But you're right, maybe this confuses some. In the next release I would use /roms/msx for the games and /roms/msx/bios for the bios files. For people who already have their games in the games directory, this is no problem, subdirectories are supported.

**Comment by kamotswind** [comment]
That sounds perfect! Still keeps the BIOS files separated but sticks to the ROM file location standard.

Thanks for the quick reply!
