### ISSUE TITLE
Games reported to run at wrong speeds - can't change model

### ISSUE THREAD

**Issue by kamotswind** [Schuemi/fMSX-go#8]
On my video about this emulator (link below) a few people have commented that the games are running at the wrong speed. One suggested I change the model for a specific game but it wouldn't let met. I could only change the NTSC/PAL setting or the memory setting. I realize this is just the first version so it isn't going to run perfect but I wanted you to be aware of this potential issue. I'm not experienced with the MSX so I thought it was running just fine. :)

https://www.youtube.com/watch?v=ahSPkKaUSSo

**Comment by Schuemi** [comment]
I'll check this and hopefully in the next release you can also change the model. 

And great video!

**Comment by kamotswind** [comment]
Thank you :)

**Comment by kamotswind** [comment]
Fixed in 20181018. Good job on the keyboard support! Thanks!

**Comment by Schuemi** [comment]
Thank you very much for the feedback.    At the moment I am on a trip through Europe, so I will not post so much.    Greetings from Croatia
